//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.BulkMessage.Service.MiddlewareService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.epg.intranet", ConfigurationName="MiddlewareService.MiddlewareServicePortType")]
    public interface MiddlewareServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doService", ReplyAction="urn:doServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EP.BulkMessage.Service.MiddlewareService.doServiceResponse doService(EP.BulkMessage.Service.MiddlewareService.doServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:doService", ReplyAction="urn:doServiceResponse")]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doServiceResponse> doServiceAsync(EP.BulkMessage.Service.MiddlewareService.doServiceRequest request);
        
        // CODEGEN: Generating message contract since the operation healthCheck is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:healthCheck", ReplyAction="urn:healthCheckResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EP.BulkMessage.Service.MiddlewareService.healthCheckResponse healthCheck(EP.BulkMessage.Service.MiddlewareService.healthCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:healthCheck", ReplyAction="urn:healthCheckResponse")]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.healthCheckResponse> healthCheckAsync(EP.BulkMessage.Service.MiddlewareService.healthCheckRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doBulkSMS", ReplyAction="urn:doBulkSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse doBulkSMS(EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:doBulkSMS", ReplyAction="urn:doBulkSMSResponse")]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse> doBulkSMSAsync(EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:doSMS", ReplyAction="urn:doSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EP.BulkMessage.Service.MiddlewareService.doSMSResponse doSMS(EP.BulkMessage.Service.MiddlewareService.doSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:doSMS", ReplyAction="urn:doSMSResponse")]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doSMSResponse> doSMSAsync(EP.BulkMessage.Service.MiddlewareService.doSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doService", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requestXML;
        
        public doServiceRequest() {
        }
        
        public doServiceRequest(string uname, string passwd, string requestXML) {
            this.uname = uname;
            this.passwd = passwd;
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doServiceResponse", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public doServiceResponse() {
        }
        
        public doServiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class healthCheckRequest {
        
        public healthCheckRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="healthCheckResponse", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class healthCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public healthCheckResponse() {
        }
        
        public healthCheckResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doBulkSMS", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doBulkSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string receiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string topic;
        
        public doBulkSMSRequest() {
        }
        
        public doBulkSMSRequest(string uname, string passwd, string message, string receiver, string topic) {
            this.uname = uname;
            this.passwd = passwd;
            this.message = message;
            this.receiver = receiver;
            this.topic = topic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doBulkSMSResponse", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doBulkSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public doBulkSMSResponse() {
        }
        
        public doBulkSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSMS", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string receiver;
        
        public doSMSRequest() {
        }
        
        public doSMSRequest(string uname, string passwd, string message, string receiver) {
            this.uname = uname;
            this.passwd = passwd;
            this.message = message;
            this.receiver = receiver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doSMSResponse", WrapperNamespace="http://services.epg.intranet", IsWrapped=true)]
    public partial class doSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.epg.intranet", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public doSMSResponse() {
        }
        
        public doSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiddlewareServicePortTypeChannel : EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiddlewareServicePortTypeClient : System.ServiceModel.ClientBase<EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType>, EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType {
        
        public MiddlewareServicePortTypeClient() {
        }
        
        public MiddlewareServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiddlewareServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiddlewareServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiddlewareServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EP.BulkMessage.Service.MiddlewareService.doServiceResponse EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doService(EP.BulkMessage.Service.MiddlewareService.doServiceRequest request) {
            return base.Channel.doService(request);
        }
        
        public string doService(string uname, string passwd, string requestXML) {
            EP.BulkMessage.Service.MiddlewareService.doServiceRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doServiceRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.requestXML = requestXML;
            EP.BulkMessage.Service.MiddlewareService.doServiceResponse retVal = ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doServiceResponse> EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doServiceAsync(EP.BulkMessage.Service.MiddlewareService.doServiceRequest request) {
            return base.Channel.doServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doServiceResponse> doServiceAsync(string uname, string passwd, string requestXML) {
            EP.BulkMessage.Service.MiddlewareService.doServiceRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doServiceRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.requestXML = requestXML;
            return ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EP.BulkMessage.Service.MiddlewareService.healthCheckResponse EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.healthCheck(EP.BulkMessage.Service.MiddlewareService.healthCheckRequest request) {
            return base.Channel.healthCheck(request);
        }
        
        public string healthCheck() {
            EP.BulkMessage.Service.MiddlewareService.healthCheckRequest inValue = new EP.BulkMessage.Service.MiddlewareService.healthCheckRequest();
            EP.BulkMessage.Service.MiddlewareService.healthCheckResponse retVal = ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).healthCheck(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.healthCheckResponse> EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.healthCheckAsync(EP.BulkMessage.Service.MiddlewareService.healthCheckRequest request) {
            return base.Channel.healthCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.healthCheckResponse> healthCheckAsync() {
            EP.BulkMessage.Service.MiddlewareService.healthCheckRequest inValue = new EP.BulkMessage.Service.MiddlewareService.healthCheckRequest();
            return ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).healthCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doBulkSMS(EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest request) {
            return base.Channel.doBulkSMS(request);
        }
        
        public string doBulkSMS(string uname, string passwd, string message, string receiver, string topic) {
            EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.message = message;
            inValue.receiver = receiver;
            inValue.topic = topic;
            EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse retVal = ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doBulkSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse> EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doBulkSMSAsync(EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest request) {
            return base.Channel.doBulkSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doBulkSMSResponse> doBulkSMSAsync(string uname, string passwd, string message, string receiver, string topic) {
            EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doBulkSMSRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.message = message;
            inValue.receiver = receiver;
            inValue.topic = topic;
            return ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doBulkSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EP.BulkMessage.Service.MiddlewareService.doSMSResponse EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doSMS(EP.BulkMessage.Service.MiddlewareService.doSMSRequest request) {
            return base.Channel.doSMS(request);
        }
        
        public string doSMS(string uname, string passwd, string message, string receiver) {
            EP.BulkMessage.Service.MiddlewareService.doSMSRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doSMSRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.message = message;
            inValue.receiver = receiver;
            EP.BulkMessage.Service.MiddlewareService.doSMSResponse retVal = ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doSMSResponse> EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType.doSMSAsync(EP.BulkMessage.Service.MiddlewareService.doSMSRequest request) {
            return base.Channel.doSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<EP.BulkMessage.Service.MiddlewareService.doSMSResponse> doSMSAsync(string uname, string passwd, string message, string receiver) {
            EP.BulkMessage.Service.MiddlewareService.doSMSRequest inValue = new EP.BulkMessage.Service.MiddlewareService.doSMSRequest();
            inValue.uname = uname;
            inValue.passwd = passwd;
            inValue.message = message;
            inValue.receiver = receiver;
            return ((EP.BulkMessage.Service.MiddlewareService.MiddlewareServicePortType)(this)).doSMSAsync(inValue);
        }
    }
}
